### ISSUE TITLE
compatibility with older versions?

### ISSUE THREAD

**Issue by c-cube** [paurkedal/ppx_regexp#1]
This looks very good, and I understand it's not mature yet, but is it feasible in the future to have compatibility with OCaml >= 4.02.*? 4.04.1 is still very recent…

**Comment by paurkedal** [comment]
4.03.0 should work, but 4.02.3 is not so straight forward: Since I use ocaml-migrate-parsetree, I use `ppx_metaquot` from Jane Street rather than from `ppx_tools`, and it is only available from version 4.03.0. The latest Ubuntu distributions at least have 4.02.3, so I guess that's one version we'd like so support at least for this to be useful.

**Comment by paurkedal** [comment]
I did a backport in the branch https://github.com/paurkedal/ppx_regexp/tree/ocaml-4.02 using metaquot from ppx\_tools.  I did a number of fixes before branching it, so I belive it's in a usable state, and it should be easy to backport fixes since few lines of real code lines are affected.

**Comment by paurkedal** [comment]
ocaml/opam-repository#9406
